service:
  name: serverless-deploy-button

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  deploy:
    handler: deploy.trigger
    events:
      - http:
          method: post
          path: deploy
