service:
  name: serverless-deploy-button

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  deploy:
    handler: deploy.trigger
    events:
      - http:
          method: post
          path: deploy
