service:
  name: serverless-deploy-button

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  second:
    handler: second.hello
    events:
      - http:
          method: get
          path: second
